export const BIOS41 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
mwd223,"BIOS 041","Marion Donoghue (lead)",she/her,"Bala Cynwyd",2023,"I've been a TRAC fellow for the past 3 years, and my favorite part of the program is always meeting and connecting with new students every semester. I think that being a good writer is a valuable skill no matter your future profession, and I love being able to help people toward that goal!","Biology major, Psychology minor",mwd223@lehigh.edu
aaw323,"BIOS 041","Alex Winters (lead)",he/him,"Allendale, NJ ",2023,"Biology ","My passion is medicine- I hope to be an orthopedic surgeon in the future. I'm a research member for the Babcock lab, a volunteer EMT, the vice president of LU AMSA, and a 'Big' for a Big Brothers Big Sisters program. TRAC has been an integral part of my time of Lehigh, and I'm grateful for having been part of it. It's exposed me to many forms of writing and has enhanced my communication skills greatly!",aaw323@lehigh.edu
bek324,"BIOS 041","Brendan Karnish",he/him,"Marlton",2024,"Computer Science and Business, Physics","Hey everyone, my name is Brendan and I am an aspiring quantum computing engineer. Some things I like to do are play ice hockey, read books, write, and restore old cars. ",bek324@lehigh.edu
ebk224,"BIOS 041","Ethan Kennedy",he/him,"Bethlehem, PA",2024,"Double Major: Psychology & Economics, Minor: Marketing","Hi, I'm Ethan!  I love to read, write, and listen to music. I love football, basketball, and soccer. One of my favorite elements of the TRAC program is the group of incredible, down to earth, friendly, smart people. I have had great experiences working as a TRAC Fellow for BUS 003 and ANTH 320.",ebk224@lehigh.edu
missing,"Niche","Alkhatib",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Cox",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Crispe",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Lebrón",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Sridhar",‎,"",‎,"","",missing@lehigh.edu,"Alumni"`;