export const BIOS42 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
jaw224,"BIOS 042","Jordyn Whalen (lead)",she/her,"Boston, MA",2024,"Biology","Hi! Outside of TRAC, I enjoy hiking, swimming and art projects. I love TRAC because it is the place at Lehigh where I feel like I can make someone else's day better and we have such a great positive community. After Lehigh, I hope to go to medical school and work in underserved areas. I have worked with BUS003 students and this semester I am doing an independent niche fellowship on community improvement for the program. ",jaw224@lehigh.edu
cai225,"BIOS 042","Charlotte Imperatore",she/her,"Riverside, CT",2025,"Joint Global Studies & MLL Major, Spanish Minor","Hey! Some of my interests include making playlists and listening to new music, thrifting and upcycling clothes, watching Arrested Development, and my involvements around campus! I'm an Associate News Editor for the Brown and White, Orientation Leader, America Reads tutor for the Community Service Office, and a member of the Lehigh Echoes Acapella group. I TRAC to help students feel more prepared for their courses, and feel the strength of the greater Lehigh community that they are a part of. I'm excited to be a TRAC fellow for BUS003 this semester, and more courses in the future!",cai225@lehigh.edu
cjm224,"BIOS 042","CJ Marina",he/him,"Stroudsburg",2024,"Accounting, Finance, History","My biggest passion is the intersection of sustainability and business! Besides that, I'm also a twin, have three other siblings, and my favorite hobby is playing with my dog Matilda Grace. Finally, Peaky Blinders is the best TV show, ever. ",cjm224@lehigh.edu
err325,"BIOS 042","Ella Rossetti",she/her,"Manasquan, New Jersey",2025,"Joint International Relations and Economics Major, Psychology Minor","Joining the TRAC program is one of the best decisions I've made. The program is comprised of an amazing group of people and being a part of it has been so fulfilling thus far. Outside of TRAC, I'm the president of the Community Growers Club. We focus on promoting sustainability on campus and among the South Bethlehem community. I'm a cellist in the Lehigh Philharmonic Orchestra and I play the piano as well. I'm looking forward for what's to come in the TRAC program and excited to continue working with such great people.",err325@lehigh.edu
eem224,"BIOS 042","Erika Maaseide",she/her,"Fairfax, VA",2025,"History, minors in English, Global Studies","Hello! I absolutely love being a TRAC fellow, and I am passionate about writing and peer education. I'm a big fan of Taylor Swift, the TV show A League of Their Own, and reading. I'm involved with other clubs on campus, such as the Lehigh History Club and SPEAK. A fun fact about me is that I have been a vegetarian for 8 years.",eem224@lehigh.edu
hul323,"BIOS 042","Huachen Liang",she/her,"Beijing, China",2023,"Acct","I enjoy kayaking and hiking. Lake Nockamixon and High Point NJ are my to go places. I’m also passionate about Asian Studies and Anthropology. I worked at the Yangguanzhai archaeological site. It was an unforgettable experience excavating potteries and, of course, skeletal remains. ",hul323@lehigh.edu
isf325,"BIOS 042","Isabella Faasuamalie",she/her,"Easton, Pennsylvania",2025,"Behavioral Neuroscience/HMS","I have always had a passion for writing and the writing process. Through the TRAC program, I have been able to fully explore this interest and many other valuable skills, including mindfulness and open communication. Beyond writing, my favorite ways to spend time are going for drives with my sister or playing with my puppies in my backyard at home. At Lehigh, I am currently premed and dedicated to pursuing a career in the medical field. ",isf325@lehigh.edu
jpc425,"BIOS 042","Julia Contino",she/her,"Vernon, New Jersey",2025,"Political Science & Journalism","Hi! I'm super passionate about people and humanity- I want to help others any way I can and I feel my most authentic self when I'm contributing to society. I'm a lefty, a feminist, and a huge Harry Potter fan! I love TRAC because not only have I had the opportunity to help countless students on my own campus, but I have learned how to better take care of myself. ",jpc425@lehigh.edu
mva225,"BIOS 042","Mariah  Alvarado ",she/her,"Lawndale, California",2025,"Sociology, Marketing","I am so excited to be working as a TRAC Fellow here at Lehigh! TRAC really empowers students inside the classroom and it’s been incredible to see the growth thus far. Asides from TRAC, I love watching crime documentaries. And when I’m back home, I love driving along the coast listening to my favorite music. ",mva225@lehigh.edu
mac425,"BIOS 042","Mary Cordova",she/her,"Reading, PA",2025,"Behavioral Neuroscience; Health, Medicine, and Society (Minor)","TRAC is important to me because it allows me to make meaningful connections with other students on campus and through peer-to-peer collaborative effort. In turn, TRAC allows me to enhance my own skills as a student and allows me to learn something new at every conference. ",mac425@lehigh.edu
rms425,"BIOS 042","Rachel Sobocinski",she/her,"Southampton, NJ",2025,"Business Information Systems","Hi! Some things I enjoy are reading, working out, and spending time with my family when I can! My first year of TRAC has been great so far and I am so excited about the upcoming semesters and the classes I'll be TRACing. Other activities I am in involved in on campus are the Women in Business Club, the BIS/AN Club, Club Field Hockey, and I am also a tutor through the CSO.",rms425@lehigh.edu
sej225,"BIOS 042","Sarah Joseph",she/her,"Dresher Pennsylvania ",2025,"English major, marketing and history minors","Hi! A few of my favorite things to do are read, listen to music, sing, and hang out with my friends. I love the TRAC program because I feel like I am actually making a difference in the Lehigh community and I’ve met some really fantastic people through the program. Although this is my first year in the program, I am already so passionate about it and cannot wait to continue throughout the rest of my Lehigh career!",sej225@lehigh.edu
ssg225,"BIOS 042","Sebastian Gaertner",he/him,"Kirkland, Washington",2025,"Cognitive Science, Data Science, Business","Hello! I enjoy listening to music and taking walks. One of my favorite things in the TRAC program is being able to read so many different peoples writing. It's amazing to see how everyone has their own unique style. I have TRAC'ed ENGR 005.",ssg225@lehigh.edu
thc325,"BIOS 042","Theodora Chacharone",she/her,"Shrewsbury, MA",2025,"English, Political Science","I TRAC because I am passionate about reading and writing and aim to use that passion to help others communicate their ideas in their work. Being a TRAC fellow has allowed me to learn more about the type of student I am and allow me to collaborate with people outside my academic disciplines. Outside of the program, I am involved in the Center for Ethics and Break the Silence. ",thc325@lehigh.edu
zja225,"BIOS 042","Zoe Aaron",she/her,"Scarsdale, New York",2025,"Majors: Psychology Minor: Mass Communications","Hi! My name is Zoe and I am a Psychology student on the developmental track. I hope to become an elementary school teacher for students with learning disabilities. I fun fact about me is that I have a twin sister! I TRAC to help other Lehigh students complete their best work, and continue to TRAC because of the amazing community it has given me. ",zja225@lehigh.edu
missing,"Niche","Kanfer",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Sokich",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Naeem",‎,"",‎,"","",missing@lehigh.edu,"Alumni"`;
