export const BIOS41 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
mwd223,"BIOS 041","Marion Donoghue",she/her,"Bala Cynwyd",2023,"Biology major, Psychology minor","I've been a TRAC fellow for the past 3 years, and my favorite part of the program is always meeting and connecting with new students every semester. I think that being a good writer is a valuable skill no matter your future profession, and I love being able to help people toward that goal!",mwd223@lehigh.edu
sna223,	"BIOS 041",	"Stephanie Alkhatib",she/her,"Bethlehem, PA",2023,"Biology","Hey everyone! I’m a pre-med student at Lehigh with the hope of attending medical school soon. Aside from being a Trac fellow, I am a peer health advisor and I do research in the Babcock lab. I’ve been a fellow for 3 years and my favorite part of the program is connecting with new students every semester. Writing and communication are so valuable in every aspect of learning, and I love that this is something we get to emphasize in a true collaborative environment.",sna223@lehigh.edu
mic324,"BIOS 041","Miles Cox",he/him,"York, Pennsylvania",2024,"Finance, Economics","Hello, my name is Miles. I am a member of the Varsity Men's Swim Team at Lehigh. I joined TRAC for my love of writing and learning, as well as my desire to help others in their writing pursuits.",mic324@lehigh.edu
bek324,"BIOS 041","Brendan Karnish",he/him,"Marlton",2024,"Computer Science and Business, Physics","Hey everyone, my name is Brendan and I am an aspiring quantum computing engineer. Some things I like to do are play ice hockey, read books, write, and restore old cars. ",bek324@lehigh.edu
ebk224,"BIOS 041","Ethan Kennedy",he/him,"Bethlehem, PA",2024,"Double Major: Psychology & Economics, Minor: Marketing","Hi, I'm Ethan!  I love to read, write, and listen to music. I love football, basketball, and soccer. One of my favorite elements of the TRAC program is the group of incredible, down to earth, friendly, smart people. I have had great experiences working as a TRAC Fellow for BUS 003 and ANTH 320.",ebk224@lehigh.edu
pll224,"BIOS 041","Paola Lebrón",she/her,"Lebanon, PA",2024,"Global Studies, International Relations, French","Hi! I am a pre-law student looking to become a family or international human rights lawyer. In my free time, I enjoy listening to music, spending time with my friends and family, traveling, and keeping up with world happenings. I hope to one day live somewhere hot and sunny! ",pll224@lehigh.edu
sas823,"BIOS 041","Sanj Sridhar",she/her,"Chatham, NJ",2023,"Integrated Business Engineering (IBE)","I love the TRAC program because of the people. TRAC 100 was one of my favorite classes at Lehigh and definitely a highlight of my time here. I made friends across the academic disciplines who all shared a passion for writing. Outside of the classroom, I love to read. Previously, I have TRAC’d BUS 003, ENGR 010, and BIOS 042",sas823@lehigh.edu
aaw323,"BIOS 041","Alex Winters",she/her,"Allendale, NJ ",2023,"Biology ","My passion is medicine- I hope to be an orthopedic surgeon in the future. I'm a research member for the Babcock lab, a volunteer EMT, the vice president of LU AMSA, and a 'Big' for a Big Brothers Big Sisters program. TRAC has been an integral part of my time of Lehigh, and I'm grateful for having been part of it. It's exposed me to many forms of writing and has enhanced my communication skills greatly!",aaw323@lehigh.edu
missing,"Niche","Crispe",‎,"",‎,"","",missing@lehigh.edu,"Alumni"`;