/**export const BUS3 = `lin,name,pronouns,picture,hometown,year,semester,yearsIn,majorMinor,info
856318382,"BUS 3 FELLOW",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
123318382,"BUS 3 FELLOW 2",she/her,123318382,"Houston, TX",2024,spring,3,Music,"Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
55612382,"BUS 3 FELLOW 3",he/him,55612382,"Brooklyn, NY",2025,fall,1,Business,"Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
856318382,"BUS 3 FELLOW 4",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
856318382,"BUS 3 FELLOW 5",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
856318382,"BUS 3 FELLOW 6",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"`;
*/

export const BUS3 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
alr523,"BUS 003","Alexa Riso (Lead)",she/her,"Chatham, NJ",2023,"Accounting, Management, Psychology","I love TRAC because of the peer learning environment it helps develop at Lehigh. I have a lot of experience working with BUS003 through the TRAC Program, and this year I am the Lead Fellow for the course. I am excited to continue to work closely with faculty and students and to participate in the unique peer community that TRAC creates.",alr523@lehigh.edu
cai225,"BUS 003","Charlotte Imperatore",she/her,"Riverside, CT",2025,"Joint Global Studies & MLL Major, Spanish Minor","Hey! Some of my interests include making playlists and listening to new music, thrifting and upcycling clothes, watching Arrested Development, and my involvements around campus! I'm an Associate News Editor for the Brown and White, Orientation Leader, America Reads tutor for the Community Service Office, and a member of the Lehigh Echoes Acapella group. I TRAC to help students feel more prepared for their courses, and feel the strength of the greater Lehigh community that they are a part of. I'm excited to be a TRAC fellow for BUS003 this semester, and more courses in the future!",cai225@lehigh.edu
rms425,"BUS 003","Rachel Sobocinski",she/her,"Southampton, NJ",2025,"Business Information Systems","Hi! Some things I enjoy are reading, working out, and spending time with my family when I can! My first year of TRAC has been great so far and I am so excited about the upcoming semesters and the classes I'll be TRACing. Other activities I am in involved in on campus are the Women in Business Club, the BIS/AN Club, Club Field Hockey, and I am also a tutor through the CSO.",rms425@lehigh.edu
jpc425,"BUS 003","Julia Contino",she/her,"Vernon, New Jersey",2025,"Political Science & Journalism","Hi! I'm super passionate about people and humanity- I want to help others any way I can and I feel my most authentic self when I'm contributing to society. I'm a lefty, a feminist, and a huge Harry Potter fan! I love TRAC because not only have I had the opportunity to help countless students on my own campus, but I have learned how to better take care of myself. ",jpc425@lehigh.edu
dmf225,"BUS 003","Dean Freiman",he/him,"Marietta, Georgia",2025,"International Relations, Psychology","Hello, everyone! My name is Dean, and some interest facts about me is that I come from a family of six, I value thrifting, listening to music, and having deep conversations with anyone who is willing to get vulnerable - no small talk is ever allowed around me! I find comfort in the extraordinary, and I love to try new things. I cherish TRAC due to the in-depth introspection and critical thinking it promotes, and I will cherish every opportunity TRAC has given me to reconnect with my passions and continue my journey of self-growth.",dmf225@lehigh.edu
cmk225,"BUS 003","Collette Kissell",she/her,"State College",2025,"Political science, minor in Womens Gender Studies, minor in International Relations and focus on domestic policy","At Lehigh I am on the cheerleading team as well as my involvement with TRAC and other philanthropic organizations. I am on the Pre-Law track in hopes of going to law school. Writing is one of the many things I find solace in as well as cheerleading. Being a TRAC fellow provides me with the outlet to write freely as well as read others writing.  ",cmk225@lehigh.edu
thc325,"BUS 003","Theodora Chacharone",she/her,"Shrewsbury, MA",2025,"English, Political Science","I TRAC because I am passionate about reading and writing and aim to use that passion to help others communicate their ideas in their work. Being a TRAC fellow has allowed me to learn more about the type of student I am and allow me to collaborate with people outside my academic disciplines. Outside of the program, I am involved in the Center for Ethics and Break the Silence. ",thc325@lehigh.edu
err325,"BUS 003","Ella Rossetti",she/her,"Manasquan, New Jersey",2025,"Joint International Relations and Economics Major, Psychology Minor","Joining the TRAC program is one of the best decisions I've made. The program is comprised of an amazing group of people and being a part of it has been so fulfilling thus far. Outside of TRAC, I'm the president of the Community Growers Club. We focus on promoting sustainability on campus and among the South Bethlehem community. I'm a cellist in the Lehigh Philharmonic Orchestra and I play the piano as well. I'm looking forward for what's to come in the TRAC program and excited to continue working with such great people.",err325@lehigh.edu
eem224,"BUS 003","Erika Maaseide",she/her,"Fairfax, VA",2025,"History, minors in English, Global Studies","Hello! I absolutely love being a TRAC fellow, and I am passionate about writing and peer education. I'm a big fan of Taylor Swift, the TV show A League of Their Own, and reading. I'm involved with other clubs on campus, such as the Lehigh History Club and SPEAK. A fun fact about me is that I have been a vegetarian for 8 years.",eem224@lehigh.edu
frh223,"BUS 003","Frannie Hottinger",she/her,"Inver Grove Heights",2023,"Management Consulting major, Business Information Systems minor","I am also on the women's basketball team at Lehigh and was able to spend this past summer interning Barcelona. One of my favorite parts of the TRAC program is that it has allowed me to create new connections and friends with people in the Lehigh community I would not have come across in my normal schedule.",frh223@lehigh.edu
bsw223,"BUS 003","Ben Wainfan",him/his,"Wallingford PA",2023,"Economics","TRAC provides me with an incredible opportunity to help others strengthen their voice and writing process. While these objectives are my top priority as a Fellow, I am also cognizant of the difficulties associated with the college transition and career development and hope to be a resource in these areas to any student I work with. Outside of TRAC, I am passionate about macroeconomics, jazz guitar, chess, philosophy, and basketball.",bsw223@lehigh.edu
lpf223,"BUS 003","Luca Florida ",he/him ,"Ridgewood, NJ",2024,"Finance, Real estate","Hello everyone. A little bit about me is that I love strategy games such as chess and poker. I also enjoy watching sports and reading. Both my parents work in journalism, and despite not going down that career path I am very grateful to be able to participate in the TRAC program and work on my writing. ",lpf223@lehigh.edu
sej225,"BUS 003","Sarah Joseph",she/her,"Dresher Pennsylvania ",2025,"English major, marketing and history minors","Hi! A few of my favorite things to do are read, listen to music, sing, and hang out with my friends. I love the TRAC program because I feel like I am actually making a difference in the Lehigh community and I’ve met some really fantastic people through the program. Although this is my first year in the program, I am already so passionate about it and cannot wait to continue throughout the rest of my Lehigh career!",sej225@lehigh.edu
mva225,"BUS 003","Mariah  Alvarado ",she/her,"Lawndale, California",2025,"Sociology, Marketing","I am so excited to be working as a TRAC Fellow here at Lehigh! TRAC really empowers students inside the classroom and it’s been incredible to see the growth thus far. Asides from TRAC, I love watching crime documentaries. And when I’m back home, I love driving along the coast listening to my favorite music. ",mva225@lehigh.edu
isf325,"BUS 003","Isabella Faasuamalie",she/her,"Easton, Pennsylvania",2025,"Behavioral Neuroscience/HMS","I have always had a passion for writing and the writing process. Through the TRAC program, I have been able to fully explore this interest and many other valuable skills, including mindfulness and open communication. Beyond writing, my favorite ways to spend time are going for drives with my sister or playing with my puppies in my backyard at home. At Lehigh, I am currently premed and dedicated to pursuing a career in the medical field. ",isf325@lehigh.edu
zja225,"BUS 003","Zoe Aaron",she/her,"Scarsdale, New York",2025,"Majors: Psychology Minor: Mass Communications","Hi! My name is Zoe and I am a Psychology student on the developmental track. I hope to become an elementary school teacher for students with learning disabilities. I fun fact about me is that I have a twin sister! I TRAC to help other Lehigh students complete their best work, and continue to TRAC because of the amazing community it has given me. ",zja225@lehigh.edu
pit223,"BUS 003","Pia Tiimob ",she/her,"Gaithersburg, Maryland",2023,"Philosophy, English","What I enjoy most about being a TRAC Fellow is getting to learn more about people and the way they think. As a philosophy major, I feel like it is so important to be able to articulate the way you feel and the way you interact with the world. I'm an avid tennis and film watcher, so don't ask me about either of these unless you're ready for a long conversation. I have previously TRAC'ed BUS003 and SOC105, and I love making connections between my major and these courses. ",pit223@lehigh.edu
mwd223,"BUS 003","Marion Donoghue",she/her,"Bala Cynwyd",2023,"I've been a TRAC fellow for the past 3 years, and my favorite part of the program is always meeting and connecting with new students every semester. I think that being a good writer is a valuable skill no matter your future profession, and I love being able to help people toward that goal!","Biology major, Psychology minor",mwd223@lehigh.edu
ajb223,"BUS 003","Abby Buckham",she/her,"Wellesley, MA",2023,"International Relations, Business, Global Studies","Hello! I am so excited to be TRACing for BUS 003 this semester and joining the Leadership Team next semester. TRAC has been a huge part of my time at Lehigh and I am excited to see all the wonderful things the program accomplishes in my last year here. Some of my interests are fashion, international travel, art history, and music.",ajb223@lehigh.edu
missing,"BUS 003","Kanfer",‎,"",‎,"","",missing@lehigh.edu
missing,"BUS 003","Sokich",‎,"",‎,"","",missing@lehigh.edu
missing,"BUS 003","Sridhar",‎,"",‎,"","",missing@lehigh.edu
missing,"BUS 003","Fett",‎,"",‎,"","",missing@lehigh.edu
missing,"BUS 003","Timob",‎,"",‎,"","",missing@lehigh.edu`;






