export const BUS3 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
cmk225,"BUS 003","Collette Kissell (lead)",she/her,"State College",2025,"Political science, minor in Womens Gender Studies, minor in International Relations and focus on domestic policy","At Lehigh I am on the cheerleading team as well as my involvement with TRAC and other philanthropic organizations. I am on the Pre-Law track in hopes of going to law school. Writing is one of the many things I find solace in as well as cheerleading. Being a TRAC fellow provides me with the outlet to write freely as well as read others writing.  ",cmk225@lehigh.edu
ajb223,"BUS 003","Abby Buckham",she/ her,"Wellesley, MA",2023,"International Relations, Business, Global Studies","Hello! I am so excited to be TRACing for BUS 003 this semester and joining the Leadership Team next semester. TRAC has been a huge part of my time at Lehigh and I am excited to see all the wonderful things the program accomplishes in my last year here. Some of my interests are fashion, international travel, art history, and music. ",ajb223@lehigh.edu
alr523,"BUS 003","Alexa Riso",she/her,"Chatham, NJ",2023,"Accounting, Management, Psychology","I love TRAC because of the peer learning environment it helps develop at Lehigh. I have a lot of experience working with BUS003 through the TRAC Program, and this year I am the Lead Fellow for the course. I am excited to continue to work closely with faculty and students and to participate in the unique peer community that TRAC creates.",alr523@lehigh.edu
crs225,"BUS 003","Carson Stotler",he/him,"Berkeley Springs, WV",2025,"Computer Science, Statistics","My career goal is to work in the tech field as a computer scientist and possibly be able to tie in my interest of sports statistics into my future career. I am really interested in weightlifting and overall health and wellness. A book I would recommend is Atomic Habits, it is a really good influential read!",crs225@lehigh.edu
cmd225,"BUS 003","Casey Dolan",she/her,"Bloomfield, NJ",2025,"Materials Science and Engineering, Economics","When I first joined TRAC, I had no idea how much of a positive impact it would have on me. I've learned so much about the value of peer to peer communication and how being vulnerable is one of our greatest strengths. I am the secretary of LU eNABLE, an on campus club dedicated to designing and 3D printing prosthetics for those in need. I am also an active member of the women's club basketball team and the society of women engineers. A TV show I recommend is New Girl. It's super funny and I've watched it five times through. I am so excited to continue being involved in the TRAC program throughout the rest of my time at Lehigh!",cmd225@lehigh.edu
dmf225,"BUS 003","Dean Freiman",he/him,"Marietta, Georgia",2025,"International Relations, Psychology","Hello, everyone! My name is Dean, and some interest facts about me is that I come from a family of six, I value thrifting, listening to music, and having deep conversations with anyone who is willing to get vulnerable - no small talk is ever allowed around me! I find comfort in the extraordinary, and I love to try new things. I cherish TRAC due to the in-depth introspection and critical thinking it promotes, and I will cherish every opportunity TRAC has given me to reconnect with my passions and continue my journey of self-growth.",dmf225@lehigh.edu
gvp225,"BUS 003","Genevieve Powell",she/her,"Windhoek, Namibia",2025,"IDEAS (concentrating in Mechanical Engineering and Sociology and Psychology)","Hi! I am an international student from Southern Africa and I have loved being here at Lehigh so far. The TRAC Program has been the most rewarding experience, and being able to connect with and learn from so many people on campus is so fulfilling. When I can, I love painting, traveling, and good coffee. ",gvp225@lehigh.edu
iss225,"BUS 003","Isabelle Spirk",she/her,"Doylestown, PA",2025,"Political Science & Environmental Studies, Asian Studies","I am interested in fields of ecology, specifically environmental humanities and sustainability policies and politics, as well as interdisciplinary studies of religion and Asian studies.  In general, I love learning.  TRAC is a natural extension of this intellectual curiosity and provides an opportunity for me to explore nontraditional topics in education, branch out by learning more about subjects I am unfamiliar with, and collaborate with peers and faculty.  Beyond TRAC, I enjoy reading books such as The Night Circus and going to the gym (at least sometimes).",iss225@lehigh.edu
jrd825,"BUS 003","Jack Davis",he/him,"Cheshire, CT",2025,"Industrial and Systems Engineering, Health Medicine and Society","Hello everyone! On my free time I enjoy playing video games with my friends or watching Netflix. I have enjoyed my time with the TRAC program so far and have been TRAC'ing ENGR 005. I would love to see the program become it's own academic department in the coming years.",jrd825@lehigh.edu
jnc425,"BUS 003","Jeremy Cohen",he/him,"Philadelphia, PA",2025,"Industrial & Systems Engineering","I love playing disc golf, watching most shows on HBO, and supporting the Philly sports teams. Through TRAC, I really enjoy helping students talk out their ideas and elevate their work. ",jnc425@lehigh.edu
jeb225,"BUS 003","Jessica Berman",she/her,"West Hartford, CT",2025,"Population Health, Chinese","Hi everyone! This is my first year being a TRAC fellow and I am so excited! I joined TRAC because I have a passion for aiding others and wanted to improve my communication skills. Outside of class, I enjoy baking, playing tennis, and watching movies. A fun fact about me is that I have been studying Mandarin for 6 years!",jeb225@lehigh.edu
jkk225,"BUS 003","Julia Klayman",she/her,"North Woodmere, New York",2025,"Global Studies, Political Science, Anthropology","Hi! Some things I like to do are cook, play tennis, and watch Grey’s Anatomy. I joined TRAC because I love to explore subjects outside of my discipline, and TRAC allows me to do just that! I love to travel, and this past summer I did an internship in Uganda and this upcoming summer I’m going back to do research!",jkk225@lehigh.edu
lrw324,"BUS 003","Lexa Winigrad",she/her,"Fanwood, NJ",2024,"Finance","I TRAC because I see how impactful this program can be for students. I find it incredibly rewarding watching my peers grow as writers over the course of a semester. I've previously TRAC'ed BUS 003 and I'm so excited to be TRACing MLL 090 this semester!",lrw324@lehigh.edu
lpf223,"BUS 003","Luca Florida ",he/him ,"Ridgewood, NJ",2024,"Finance, Real estate","Hello everyone. A little bit about me is that I love strategy games such as chess and poker. I also enjoy watching sports and reading. Both my parents work in journalism, and despite not going down that career path I am very grateful to be able to participate in the TRAC program and work on my writing. ",lpf223@lehigh.edu
mra225,"BUS 003","Marissa Argen",she/her,"Boonton Twp, NJ",2025,"Biology, Spanish & Hispanic Studies","Hi! I'm currently on the pre-health track with the intention to pursue a career as either a physician assistant or a veterinarian. In my free time, I enjoy drawing, painting, reading, listening to music, and being outside! I am incredibly grateful to be a part of TRAC because it has allowed me to meet new friends and continue to explore reading/writing while helping other students succeed. ",mra225@lehigh.edu
nid225,"BUS 003","Niija Douglas",she/her,"West Hartford",2025,"Major: Computer Science Engineering, Minors: Data Science, Economics","Hi! Some of my hobbies include playing lacrosse and trying new foods. I TRAC because I have always loved helping improve the work of my friends and was excited to be able to do so on a larger scale. I recommend  the Netflix series Money Heist!",nid225@lehigh.edu
pit223,"BUS 003","Pia Tiimob ",she/her,"Gaithersburg, Maryland",2023,"Philosophy, English","What I enjoy most about being a TRAC Fellow is getting to learn more about people and the way they think. As a philosophy major, I feel like it is so important to be able to articulate the way you feel and the way you interact with the world. I'm an avid tennis and film watcher, so don't ask me about either of these unless you're ready for a long conversation. I have previously TRAC'ed BUS003 and SOC105, and I love making connections between my major and these courses. ",pit223@lehigh.edu
rfd225,"BUS 003","Rylin Douthit",she/her,"Wilmette, IL",2025,"Major: Psychology and Health, Medicine, & Society Minor: Spanish ","Hi! I am super grateful to be a part of the TRAC program and it is something I look forward to each day. I am currently TRACing the ENGR 005 class and I've really enjoyed the opportunity to work with students in a major concentration that I've never been exposed to. Looking forward to being part of this program throughout my next semesters at Lehigh!",rfd225@lehigh.edu
smt225,"BUS 003","Sonia Trinkle",she/her,"Westport, CT",2025,"Biomechanical Engineering","Hi! Some of my hobbies are running, yoga, and listening to music & podcasts. A fun fact about me is that I have dual citizenship in the U.S. and Ireland. My favorite part about the TRAC program is helping other students with their writing while also developing and transforming my own abilities as a scholar. ",smt225@lehigh.edu
trg224,"BUS 003","Thiyara Girihagama",she/her,"Colombo, Sri Lanka",2024,"B.S Economics and Computer Science","I'm an international student from Sri Lanka. In my free time I enjoy playing tennis, hanging out with friends, reading, and playing piano. I also enjoy observational astronomy and astrophysics research. My other research entails projects in the field of financial engineering/quantitative finance. I love TRAC for the amazing people I've met and conversations I've had, as well as for how it helps me keep my goals and ideas grounded and in perspective. I have previously TRAC'ed ENGR005 and REL090. ",trg224@lehigh.edu
missing,"Niche","Mack",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Mucharemba",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","MacMahon",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
hideMe,"BUS 003","",‎,"",‎,"","",missing@lehigh.edu`;






