id,assignment,name,pronouns,hometown,year,majorMinor,info,email
ebk224,"ANTH 320","Ethan Kennedy",he/him,"Bethlehem, PA",2024,"Double Major: Psychology & Economics, Minor: Marketing","Hi, I'm Ethan!  I love to read, write, and listen to music. I love football, basketball, and soccer. One of my favorite elements of the TRAC program is the group of incredible, down to earth, friendly, smart people. I have had great experiences working as a TRAC Fellow for BUS 003 and ANTH 320.",ebk224@lehigh.edu
hnv223,"ANTH 320","Helena Volpe",she/her,"Lafayette Hill, PA",2023,"International Relations, Russian","Some things I enjoy are listening to music, being outdoors, and learning about other cultures. I TRAC because it is a unique program where I can combine my writing skills with my love of helping others. I am excited to get to know students and collaborate with them to reach their full potential and actualize their goals as writers. Previously I have TRAC'ed BUS 003 and ANTH 011.",hnv223@lehigh.edu
cai225,"BUS 003","Charlotte Imperatore",she/her,"Riverside, CT",2025,"Joint Global Studies & MLL Major, Spanish Minor","Hey! Some of my interests include making playlists and listening to new music, thrifting and upcycling clothes, watching Arrested Development, and my involvements around campus! I'm an Associate News Editor for the Brown and White, Orientation Leader, America Reads tutor for the Community Service Office, and a member of the Lehigh Echoes Acapella group. I TRAC to help students feel more prepared for their courses, and feel the strength of the greater Lehigh community that they are a part of. I'm excited to be a TRAC fellow for BUS003 this semester, and more courses in the future!",cai225@lehigh.edu
rms425,"BUS 003","Rachel Sobocinski",she/her,"Southampton, NJ",2025,"Business Information Systems","Hi! Some things I enjoy are reading, working out, and spending time with my family when I can! My first year of TRAC has been great so far and I am so excited about the upcoming semesters and the classes I'll be TRACing. Other activities I am in involved in on campus are the Women in Business Club, the BIS/AN Club, Club Field Hockey, and I am also a tutor through the CSO.",rms425@lehigh.edu
jpc425,"BUS 003","Julia Contino",she/her,"Vernon, New Jersey",2025,"Political Science & Journalism","Hi! I'm super passionate about people and humanity- I want to help others any way I can and I feel my most authentic self when I'm contributing to society. I'm a lefty, a feminist, and a huge Harry Potter fan! I love TRAC because not only have I had the opportunity to help countless students on my own campus, but I have learned how to better take care of myself. ",jpc425@lehigh.edu
dmf225,"BUS 003","Dean Freiman",he/him,"Marietta, Georgia",2025,"International Relations, Psychology","Hello, everyone! My name is Dean, and some interest facts about me is that I come from a family of six, I value thrifting, listening to music, and having deep conversations with anyone who is willing to get vulnerable - no small talk is ever allowed around me! I find comfort in the extraordinary, and I love to try new things. I cherish TRAC due to the in-depth introspection and critical thinking it promotes, and I will cherish every opportunity TRAC has given me to reconnect with my passions and continue my journey of self-growth.",dmf225@lehigh.edu
cmk225,"BUS 003","Collette Kissell",she/her,"State College",2025,"Political science, minor in Womens Gender Studies, minor in International Relations and focus on domestic policy","At Lehigh I am on the cheerleading team as well as my involvement with TRAC and other philanthropic organizations. I am on the Pre-Law track in hopes of going to law school. Writing is one of the many things I find solace in as well as cheerleading. Being a TRAC fellow provides me with the outlet to write freely as well as read others writing.  ",cmk225@lehigh.edu
alr523,"BUS 003","Alexa Riso",she/her,"Chatham, NJ",2023,"Accounting, Management, Psychology","I love TRAC because of the peer learning environment it helps develop at Lehigh. I have a lot of experience working with BUS003 through the TRAC Program, and this year I am the Lead Fellow for the course. I am excited to continue to work closely with faculty and students and to participate in the unique peer community that TRAC creates.",alr523@lehigh.edu
thc325,"BUS 003","Theodora Chacharone",she/her,"Shrewsbury, MA",2025,"English, Political Science","I TRAC because I am passionate about reading and writing and aim to use that passion to help others communicate their ideas in their work. Being a TRAC fellow has allowed me to learn more about the type of student I am and allow me to collaborate with people outside my academic disciplines. Outside of the program, I am involved in the Center for Ethics and Break the Silence. ",thc325@lehigh.edu
err325,"BUS 003","Ella Rossetti",she/her,"Manasquan, New Jersey",2025,"Joint International Relations and Economics Major, Psychology Minor","Joining the TRAC program is one of the best decisions I've made. The program is comprised of an amazing group of people and being a part of it has been so fulfilling thus far. Outside of TRAC, I'm the president of the Community Growers Club. We focus on promoting sustainability on campus and among the South Bethlehem community. I'm a cellist in the Lehigh Philharmonic Orchestra and I play the piano as well. I'm looking forward for what's to come in the TRAC program and excited to continue working with such great people.",err325@lehigh.edu
eem224,"BUS 003","Erika Maaseide",she/her,"Fairfax, VA",2025,"History, minors in English, Global Studies","Hello! I absolutely love being a TRAC fellow, and I am passionate about writing and peer education. I'm a big fan of Taylor Swift, the TV show A League of Their Own, and reading. I'm involved with other clubs on campus, such as the Lehigh History Club and SPEAK. A fun fact about me is that I have been a vegetarian for 8 years.",eem224@lehigh.edu
frh223,"BUS 003","Frannie Hottinger",she/her,"Inver Grove Heights",2023,"Management Consulting major, Business Information Systems minor","I am also on the women's basketball team at Lehigh and was able to spend this past summer interning Barcelona. One of my favorite parts of the TRAC program is that it has allowed me to create new connections and friends with people in the Lehigh community I would not have come across in my normal schedule.",frh223@lehigh.edu
bsw223,"BUS 003","Ben Wainfan",him/his,"Wallingford PA",2023,"Economics","TRAC provides me with an incredible opportunity to help others strengthen their voice and writing process. While these objectives are my top priority as a Fellow, I am also cognizant of the difficulties associated with the college transition and career development and hope to be a resource in these areas to any student I work with. Outside of TRAC, I am passionate about macroeconomics, jazz guitar, chess, philosophy, and basketball.",bsw223@lehigh.edu
lpf223,"BUS 003","Luca Florida ",he/him ,"Ridgewood, NJ",2024,"Finance, Real estate","Hello everyone. A little bit about me is that I love strategy games such as chess and poker. I also enjoy watching sports and reading. Both my parents work in journalism, and despite not going down that career path I am very grateful to be able to participate in the TRAC program and work on my writing. ",lpf223@lehigh.edu
sej225,"BUS 003","Sarah Joseph",she/her,"Dresher Pennsylvania ",2025,"English major, marketing and history minors","Hi! A few of my favorite things to do are read, listen to music, sing, and hang out with my friends. I love the TRAC program because I feel like I am actually making a difference in the Lehigh community and I’ve met some really fantastic people through the program. Although this is my first year in the program, I am already so passionate about it and cannot wait to continue throughout the rest of my Lehigh career!",sej225@lehigh.edu
mva225,"BUS 003","Mariah  Alvarado ",she/her,"Lawndale, California",2025,"Sociology, Marketing","I am so excited to be working as a TRAC Fellow here at Lehigh! TRAC really empowers students inside the classroom and it’s been incredible to see the growth thus far. Asides from TRAC, I love watching crime documentaries. And when I’m back home, I love driving along the coast listening to my favorite music. ",mva225@lehigh.edu
isf325,"BUS 003","Isabella Faasuamalie",she/her,"Easton, Pennsylvania",2025,"Behavioral Neuroscience/HMS","I have always had a passion for writing and the writing process. Through the TRAC program, I have been able to fully explore this interest and many other valuable skills, including mindfulness and open communication. Beyond writing, my favorite ways to spend time are going for drives with my sister or playing with my puppies in my backyard at home. At Lehigh, I am currently premed and dedicated to pursuing a career in the medical field. ",isf325@lehigh.edu
zja225,"BUS 003","Zoe Aaron",she/her,"Scarsdale, New York",2025,"Majors: Psychology Minor: Mass Communications","Hi! My name is Zoe and I am a Psychology student on the developmental track. I hope to become an elementary school teacher for students with learning disabilities. I fun fact about me is that I have a twin sister! I TRAC to help other Lehigh students complete their best work, and continue to TRAC because of the amazing community it has given me. ",zja225@lehigh.edu
pit223,"BUS 003","Pia Tiimob ",she/her,"Gaithersburg, Maryland",2023,"Philosophy, English","What I enjoy most about being a TRAC Fellow is getting to learn more about people and the way they think. As a philosophy major, I feel like it is so important to be able to articulate the way you feel and the way you interact with the world. I'm an avid tennis and film watcher, so don't ask me about either of these unless you're ready for a long conversation. I have previously TRAC'ed BUS003 and SOC105, and I love making connections between my major and these courses. ",pit223@lehigh.edu
mwd223,"BUS 003","Marion Donoghue",she/her,"Bala Cynwyd",2023,"I've been a TRAC fellow for the past 3 years, and my favorite part of the program is always meeting and connecting with new students every semester. I think that being a good writer is a valuable skill no matter your future profession, and I love being able to help people toward that goal!","Biology major, Psychology minor",mwd223@lehigh.edu
ajb223,"BUS 003","Abby Buckham",she/ her,"Wellesley, MA",2023,"International Relations, Business, Global Studies","Hello! I am so excited to be TRACing for BUS 003 this semester and joining the Leadership Team next semester. TRAC has been a huge part of my time at Lehigh and I am excited to see all the wonderful things the program accomplishes in my last year here. Some of my interests are fashion, international travel, art history, and music. ",ajb223@lehigh.edu
aaw323,"CEE/EES 379","Alex Winters ",he/him,"Allendale, NJ ",2023,"Biology ","My passion is medicine- I hope to be an orthopedic surgeon in the future. I'm a research member for the Babcock lab, a volunteer EMT, the vice president of LU AMSA, and a 'Big' for a Big Brothers Big Sisters program. TRAC has been an integral part of my time of Lehigh, and I'm grateful for having been part of it. It's exposed me to many forms of writing and has enhanced my communication skills greatly!",aaw323@lehigh.edu
tia323,"ENGR 005","Tanya Andino",she/her ,"Dallas, TX ",2023,"Political Science, Women Gender and Sexuality Studies Double Major, Health Medicine and Society Minor ","Hi! I am currently working on applying to law school, so my current hobbies include relaxing by watching British Bake-off and reading the New York Times. Normally, I love to watch movies,  read and listen to podcasts. I am currently reading Verity and It Ends With Us. I love TRAC-ing Engineering 005 and have also TRAC'd BIS 003.  ",tia323@lehigh.edu
ajk324,"ENGR 005","Ashley Kim",she/her,"Wood Ridge, NJ",2024,"International Relations and Economics, Asian Studies","I am passionate about the TRAC program because it provides me with the opportunity to connect with other Lehigh students and to help students navigate the writing process. Some things I enjoy doing are puzzles, yoga, and watching movies. I think having a work-life balance is incredibly important, so I love that the TRAC program sees mental health and mindfulness as a priority!",ajk324@lehigh.edu
mac425,"ENGR 005","Mary Cordova",she/her,"Reading, PA",2025,"Behavioral Neuroscience; Health, Medicine, and Society (Minor)","TRAC is important to me because it allows me to make meaningful connections with other students on campus and through peer-to-peer collaborative effort. In turn, TRAC allows me to enhance my own skills as a student and allows me to learn something new at every conference. ",mac425@lehigh.edu
huh224,"ENGR 005","Huda Hagos",she/her,"Philadelphia, Pennsylvania",2024,"Environmental Studies, Political Science","I'm extremely passionate about all things environmental and social justice. I love to learn how people think and explore the world through different people's eyes. TRAC provides me with the perfect opportunity to do so. I get to learn from people of different majors and explore the writing process from their perspectives.",huh224@lehigh.edu
jrd825,"ENGR 005","Jack Davis",he/him,"Cheshire, CT",2025,"Industrial and Systems Engineering, Health Medicine and Society","Hello everyone! On my free time I enjoy playing video games with my friends or watching Netflix. I have enjoyed my time with the TRAC program so far and have been TRAC'ing ENGR 005. I would love to see the program become it's own academic department in the coming years.",jrd825@lehigh.edu
crs225,"ENGR 005","Carson Stotler",he/him,"Berkeley Springs, WV",2025,"Computer Science, Statistics","My career goal is to work in the tech field as a computer scientist and possibly be able to tie in my interest of sports statistics into my future career. I am really interested in weightlifting and overall health and wellness. A book I would recommend is Atomic Habits, it is a really good influential read!",crs225@lehigh.edu
jkk225,"ENGR 005","Julia Klayman",she/her,"North Woodmere, New York",2025,"Global Studies, Political Science, Anthropology","Hi! Some things I like to do are cook, play tennis, and watch Grey’s Anatomy. I joined TRAC because I love to explore subjects outside of my discipline, and TRAC allows me to do just that! I love to travel, and this past summer I did an internship in Uganda and this upcoming summer I’m going back to do research!",jkk225@lehigh.edu
smt225,"ENGR 005","Sonia Trinkle",she/her,"Westport, CT",2025,"Biomechanical Engineering","Hi! Some of my hobbies are running, yoga, and listening to music & podcasts. A fun fact about me is that I have dual citizenship in the U.S. and Ireland. My favorite part about the TRAC program is helping other students with their writing while also developing and transforming my own abilities as a scholar. ",smt225@lehigh.edu
jeb225,"ENGR 005","Jessica Berman",she/her,"West Hartford, CT",2025,"Population Health, Chinese","Hi everyone! This is my first year being a TRAC fellow and I am so excited! I joined TRAC because I have a passion for aiding others and wanted to improve my communication skills. Outside of class, I enjoy baking, playing tennis, and watching movies. A fun fact about me is that I have been studying Mandarin for 6 years!",jeb225@lehigh.edu
ssg225,"ENGR 005","Sebastian Gaertner",he/him,"Kirkland, Washington",2025,"Cognitive Science, Data Science, Business","Hello! I enjoy listening to music and taking walks. One of my favorite things in the TRAC program is being able to read so many different peoples writing. It's amazing to see how everyone has their own unique style. I have TRAC'ed ENGR 005.",ssg225@lehigh.edu
rfd225,"ENGR 005","Rylin Douthit",she/her,"Wilmette, IL",2025,"Major: Psychology and Health, Medicine, & Society Minor: Spanish ","Hi! I am super grateful to be a part of the TRAC program and it is something I look forward to each day. I am currently TRACing the ENGR 005 class and I've really enjoyed the opportunity to work with students in a major concentration that I've never been exposed to. Looking forward to being part of this program throughout my next semesters at Lehigh!",rfd225@lehigh.edu
gek224,"ENGR 005","Gabrielle",she/her,"North Caldwell, NJ",2024,"Major: Management Minor: Sociology","I am a junior at Lehigh who is studies business, loves writing, and enjoys having fun with friends! A fun fact about me is that I have a younger brother and that I am allergic to peanuts. A TV show I recommend is ""Glee"" because it is my favorite show and the music is incredible. I decided to join TRAC to immerse myself in a community of hard-working, talented, and passionate individuals! ",gek224@lehigh.edu
bek324,"ENGR 005","Brendan Karnish",he/him,"Marlton",2024,"Computer Science and Business, Physics","Hey everyone, my name is Brendan and I am an aspiring quantum computing engineer. Some things I like to do are play ice hockey, read books, write, and restore old cars. ",bek324@lehigh.edu
nid225,"ENGR 005","Niija Douglas",she/her,"West Hartford",2025,"Major: Computer Science Engineering, Minors: Data Science, Economics","Hi! Some of my hobbies include playing lacrosse and trying new foods. I TRAC because I have always loved helping improve the work of my friends and was excited to be able to do so on a larger scale. I recommend  the Netflix series Money Heist!",nid225@lehigh.edu
cjm224,"ENGR 005","Cj",marina,"Stroudsburg",2024,"Accounting, Finance, History","My biggest passion is the intersection of sustainability and business! Besides that, I'm also a twin, have three other siblings, and my favorite hobby is playing with my dog Matilda Grace. Finally, Peaky Blinders is the best TV show, ever. ",cjm224@lehigh.edu
ajp224,"ENGR 005","Alex Patti",he/him,"Blue Bell, PA",2024,"Finance, Accounting","Hello! Some hobbies of mine are listening to music, watching movies, and playing golf. I am a member of the swim team and have been doing it competitively for over 10 years. I am excited to continue to work as a TRAC Fellow and get exposure to new courses each semester. I have previously worked with BUS003.",ajp224@lehigh.edu
gvp225,"ENGR 005","Genevieve Powell",she/her,"Windhoek, Namibia",2025,"IDEAS (concentrating in Mechanical Engineering and Sociology and Psychology)","Hi! I am an international student from Southern Africa and I have loved being here at Lehigh so far. The TRAC Program has been the most rewarding experience, and being able to connect with and learn from so many people on campus is so fulfilling. When I can, I love painting, traveling, and good coffee. ",gvp225@lehigh.edu
iss225,"ENGR 005","Isabelle Spirk",she/her,"Doylestown, PA",2025,"Political Science & Environmental Studies, Asian Studies","I am interested in fields of ecology, specifically environmental humanities and sustainability policies and politics, as well as interdisciplinary studies of religion and Asian studies.  In general, I love learning.  TRAC is a natural extension of this intellectual curiosity and provides an opportunity for me to explore nontraditional topics in education, branch out by learning more about subjects I am unfamiliar with, and collaborate with peers and faculty.  Beyond TRAC, I enjoy reading books such as The Night Circus and going to the gym (at least sometimes).",iss225@lehigh.edu
cmd225,"ENGR 005","Casey Dolan",she/her,"Bloomfield, NJ",2025,"Materials Science and Engineering, Economics","When I first joined TRAC, I had no idea how much of a positive impact it would have on me. I've learned so much about the value of peer to peer communication and how being vulnerable is one of our greatest strengths. I am the secretary of LU eNABLE, an on campus club dedicated to designing and 3D printing prosthetics for those in need. I am also an active member of the women's club basketball team and the society of women engineers. A TV show I recommend is New Girl. It's super funny and I've watched it five times through. I am so excited to continue being involved in the TRAC program throughout the rest of my time at Lehigh!",cmd225@lehigh.edu
mra225,"ENGR 005","Marissa Argen",she/her,"Boonton Twp, NJ",2025,"Biology, Spanish & Hispanic Studies","Hi! I'm currently on the pre-health track with the intention to pursue a career as either a physician assistant or a veterinarian. In my free time, I enjoy drawing, painting, reading, listening to music, and being outside! I am incredibly grateful to be a part of TRAC because it has allowed me to meet new friends and continue to explore reading/writing while helping other students succeed. ",mra225@lehigh.edu
akt224,"ENGR 005","Akari Takahashi",she/her,"Tokyo",2024,"Biology, HMS","During my free time, I like to listen to music, draw, play tennis, and watch musicals. Since I grew up in Japan, the cultural background may be different from that of native speakers, but I would like to use my unique perspective and way of thinking in TRAC. Previously I have TRAC'ed BUS 003 and BIOS 042. ",akt224@lehigh.edu
jnc425,"ENGR 005","Jeremy Cohen",he/him,"Philadelphia, PA",2025,"Industrial & Systems Engineering","I love playing disc golf, watching most shows on HBO, and supporting the Philly sports teams. Through TRAC, I really enjoy helping students talk out their ideas and elevate their work. ",jnc425@lehigh.edu
cjs323,"LT","Caroline Spindel",she/her,"Murfreesboro, TN",2023,"IDEAS, Electrical Engineering, Psychology, Philosophy","The 2022-2023 school year is my third year as a TRAC Fellow. I have TRAC'ed four courses (ENGR 095, REL 122, MLL 090), as well as working as the Lead Fellow for ANTH 011. For the 2022-2023 school year, I am working as a Veteran Fellow Mentor Fellow as a member of the Leadership Team. My favorite aspects of TRAC are conferencing, hosting Veteran Fellow Seminars, and participating in the recruitment process. ",cjs323@lehigh.edu
mig223,"LT","Michaela Gualano",she/her,"Mamaroneck, NY",2023,"Finance, Entrepreneurship & Real Estate ","I ran to be an Associate Fellow Mentor Fellow on the basis of wanting to emulate the idea of “Process of Product” in my teaching, as I want other fellows to know that it’s about learning along the way. It is about discovering yourself, new ways to help other students, and new ways to learn/ teach. ",mig223@lehigh.edu
cab223,"LT","Charlotte Brown",she/her,"Westchester, NY",2023,"Philosophy, Graphic Design, Marketing","Hiya! I love reading and writing and the TRAC program has proven to be the perfect application of those passions, with the addition of helping others and being part of a caring community. In my free time, I teach yoga at Taylor Gym and enjoy listening to music and spending time with my friends.",cab223@lehigh.edu
cep223,"LT","Caroline Palmer",she/her,"Princeton Junction, NJ",2023,"Biology, Religion","Here at Lehigh, I am the president of the LU Bhangra dance team, I am a Martindale Honors Associate (ask me about this, it's so cool!), and I have my own embroidery business. Next year, I'll be in dental school. I TRAC because TRAC gives me a voice and it allows me to learn, teach and reflect. Being surrounded by different, charismatic people allows for such a wonderful exchange of ideas! Specifically in TRAC I am a veteran fellow mentor fellow. ",cep223@lehigh.edu
bcn223,"LT","Brian Nasielski",he/him,"Mount Laurel, NJ",2023,"Chemical Engineering and Biochemistry Double Major","I am currently a senior at Lehigh and serving as a Veteran-Mentor Fellow on the Leadership Team. During my time in the program I have worked closely with ENG005, BIOS042, EES379 and the senior engineering capstone design course. Being in the TRAC program has helped shape the way I approach problems and communicate with others, and it has proven to be critical in my approach to other involvements such as undergraduate research, summer internships, and even being a part of Greek Life at Lehigh. Outside of the program and In my free time I enjoy exercising and spending time outside, especially down the shore.  ",bcn223@lehigh.edu
jjc422,"LT","John Cascio",he/him,"Bellmore, NY",2023,"Mechanical Engineering and Finance, Aerospace Engineering and Economics","I am currently the Managing Fellow of the TRAC Program, and in the past I was a member of the LT and TRAC'ed courses such as HSE 472, MAT 033, BUS 003, and ENGR 005.  On campus, I am a Head Gryphon in Taylor House and also a member of Phi Sigma Pi Honors Fraternity, where I served as Treasurer and President.  Some of my favorite hobbies include attending concerts, going to theme parks, and skiing.  I am also interested in astronomy research and other aerospace developments. ",jjc422@lehigh.edu
hul323,"MLL 090","Huachen Liang",she/her,"Beijing, China",2023,"Acct","I enjoy kayaking and hiking. Lake Nockamixon and High Point NJ are my to go places. I’m also passionate about Asian Studies and Anthropology. I worked at the Yangguanzhai archaeological site. It was an unforgettable experience excavating potteries and, of course, skeletal remains. ",hul323@lehigh.edu
lrw324,"MLL 090","Lexa Winigrad",she/her,"Fanwood, NJ",2024,"Finance","I TRAC because I see how impactful this program can be for students. I find it incredibly rewarding watching my peers grow as writers over the course of a semester. I've previously TRAC'ed BUS 003 and I'm so excited to be TRACing MLL 090 this semester!",lrw324@lehigh.edu
jct324,"Niche","Joss Tripoli",they/them,"Perkasie, PA",2023,"Computer Science, Japanese","Hello! Some things I like to do are listen to music, juggle, and make art. Software and web development are passions of mine, so I am excited to be working on the TRAC website this semester. I hope to improve the website's branding & consistency, presence, information, and functionality. Previously I have TRAC'ed BUS 003 and BIOS 042.",jct324@lehigh.edu
trg224,"Niche","Thiyara Girihagama",she/her,"Colombo, Sri Lanka",2024,"B.S Economics and Computer Science","I'm an international student from Sri Lanka. In my free time I enjoy playing tennis, hanging out with friends, reading, and playing piano. I also enjoy observational astronomy and astrophysics research. My other research entails projects in the field of financial engineering/quantitative finance. I love TRAC for the amazing people I've met and conversations I've had, as well as for how it helps me keep my goals and ideas grounded and in perspective. I have previously TRAC'ed ENGR005 and REL090. ",trg224@lehigh.edu
krm422,"Niche","Katelyn McNamara",she/her,"Alexandria, Virginia",2022 for undergraduate degree (2023 for graduate degree),"Masters in Management, Major in Architecture, Minor in Marketing","I am a current graduate student in Lehigh's Master's in Management program. This is my 4th year as a TRAC Fellow and it has been one of my most rewarding experiences at Lehigh. During the past few years, I have worked with the Sociology and Business Communications classes as well as working as a Fellow while studying abroad in Florence. Currently, I am working as a Niche Fellow with the TRAC 100 seminar and am assisting our Associate Fellows as they complete their Self-Design projects. I love the work that we do in TRAC and I wish every student at Lehigh could work with a Fellow at some point in their education.",krm422@lehigh.edu
agk423,"Niche","Alex Kline",he/him,"Mountain Top, PA",2023,"IDEAS B.S., C.S. B.S.","I love skiing and making music. I love building software. I am totally obsessed with cars and auto racing, especially F1. I like TRAC because it gets students more involved in the writing process and helps many underclassmen transition to writing in college. ",agk423@lehigh.edu
jaw224,"Niche","Jordyn Whalen",she/her,"Boston, MA",2024,"Biology","Hi! Outside of TRAC, I enjoy hiking, swimming and art projects. I love TRAC because it is the place at Lehigh where I feel like I can make someone else's day better and we have such a great positive community. After Lehigh, I hope to go to medical school and work in underserved areas. I have worked with BUS003 students and this semester I am doing an independent niche fellowship on community improvement for the program. ",jaw224@lehigh.edu
jbp223,"PSYCH 203","Jordyn Pykon",she/her,"New York City ",2023,"Science Journalism, Documentary Storymaking, Environmental Studies ","Hi! I'm a senior at Lehigh University interested in visual storytelling through journalism and documentary film. When I'm not writing or making videos, I  enjoy playing on the Ultimate Frisbee Team, being a Diversity Peer Educator, reading books, and of course, being a TRAC Fellow. One fun fact about me is that I can take sunglasses off my face with my feet. ",jbp223@lehigh.edu
css223,"PSYCH 203","Cat Spellman",she/her,"Newtown Square, PA",2023,"English, Environmental Studies","Hi! I'm a senior currently pursuing my accelerated Master's in secondary education while getting my undergrad degrees in English and Environmental Studies. I'm on the Women's Ultimate Frisbee team at Lehigh, love to go hiking in the area, and am a big fan Bethlehem's festivals. As a TRAC fellow, I value connecting with other students, sharing my passion for writing, and having meaningful conversations. ",css223@lehigh.edu
aka223,"REL 090","Amaya Apolinario",she/her,"Clinton, NC",2023,"English, Japanese","Hi there! I am a part of the Marching 97 at Lehigh and love creative writing. I'm also a huge Carolina Hurricanes fan, and my favorite novel is The Left Hand of Darkness by Ursula K. Le Guin. I highly recommend it if you ever get the chance to give it a read!",aka223@lehigh.edu
skb324,"SOC 313","Sam Barney-Gibbs",he/him,"Carlsbad, CA",2024,"Journalism, Political Science, Philosophy, Global Studies","Hi! I have been extremely dedicated to writing since a young age and find it to be a core part of my everyday life. I hope to use my passion of the written and spoken word as a journalist, poet, speechwriter, politician, or wherever else I end up channeling my energy. I spend most of my time in The Brown and White newsroom, on the tennis court, binge-watching bad comedies, attempting to bake as much as possible, and always drinking Saxbys coffee. I am always happy and eager to talk to new people, so please feel free to reach out!",skb324@lehigh.edu