export const CSE252 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
agk423,"CSE 252","Alex Kline (lead)",he/him,"Mountain Top, PA",2023,"IDEAS B.S., C.S. B.S.","I love skiing and making music. I love building software. I am totally obsessed with cars and auto racing, especially F1. I like TRAC because it gets students more involved in the writing process and helps many underclassmen transition to writing in college. ",agk423@lehigh.edu
skb324,"CSE 252","Sam Barney-Gibbs",he/him,"Carlsbad, CA",2024,"Journalism, Political Science, Philosophy, Global Studies","Hi! I have been extremely dedicated to writing since a young age and find it to be a core part of my everyday life. I hope to use my passion of the written and spoken word as a journalist, poet, speechwriter, politician, or wherever else I end up channeling my energy. I spend most of my time in The Brown and White newsroom, on the tennis court, binge-watching bad comedies, attempting to bake as much as possible, and always drinking Saxbys coffee. I am always happy and eager to talk to new people, so please feel free to reach out!",skb324@lehigh.edu
ajp224,"CSE 252","Alex Patti",he/him,"Blue Bell, PA",2024,"Finance, Accounting","Hello! Some hobbies of mine are listening to music, watching movies, and playing golf. I am a member of the swim team and have been doing it competitively for over 10 years. I am excited to continue to work as a TRAC Fellow and get exposure to new courses each semester. I have previously worked with BUS003.",ajp224@lehigh.edu
jbp223,"CSE 252","Jordyn Pykon",she/her,"New York City ",2023,"Science Journalism, Documentary Storymaking, Environmental Studies ","Hi! I'm a senior at Lehigh University interested in visual storytelling through journalism and documentary film. When I'm not writing or making videos, I  enjoy playing on the Ultimate Frisbee Team, being a Diversity Peer Educator, reading books, and of course, being a TRAC Fellow. One fun fact about me is that I can take sunglasses off my face with my feet. ",jbp223@lehigh.edu
css223,"CSE 252","Cat Spellman",she/her,"Newtown Square, PA",2023,"English, Environmental Studies","Hi! I'm a senior currently pursuing my accelerated Master's in secondary education while getting my undergrad degrees in English and Environmental Studies. I'm on the Women's Ultimate Frisbee team at Lehigh, love to go hiking in the area, and am a big fan Bethlehem's festivals. As a TRAC fellow, I value connecting with other students, sharing my passion for writing, and having meaningful conversations. ",css223@lehigh.edu
missing,"Niche","Lee",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Timob",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
hideMe,"CSE 252","",‎,"",‎,"","",missing@lehigh.edu,"Speaking Fellows"
hideMe,"CSE 252","",‎,"",‎,"","",missing@lehigh.edu,"Speaking Fellows"`;

