export const ENGR5 = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
missing,"ENGR 005","MacMahon (Lead)",‎,"",‎,"","",missing@lehigh.edu
tia323,"ENGR 005","Tanya Andino",she/her ,"Dallas, TX ",2023,"Political Science, Women Gender and Sexuality Studies Double Major, Health Medicine and Society Minor ","Hi! I am currently working on applying to law school, so my current hobbies include relaxing by watching British Bake-off and reading the New York Times. Normally, I love to watch movies,  read and listen to podcasts. I am currently reading Verity and It Ends With Us. I love TRAC-ing Engineering 005 and have also TRAC'd BIS 003.  ",tia323@lehigh.edu
ajk324,"ENGR 005","Ashley Kim",she/her,"Wood Ridge, NJ",2024,"International Relations and Economics, Asian Studies","I am passionate about the TRAC program because it provides me with the opportunity to connect with other Lehigh students and to help students navigate the writing process. Some things I enjoy doing are puzzles, yoga, and watching movies. I think having a work-life balance is incredibly important, so I love that the TRAC program sees mental health and mindfulness as a priority!",ajk324@lehigh.edu
mac425,"ENGR 005","Mary Cordova",she/her,"Reading, PA",2025,"Behavioral Neuroscience; Health, Medicine, and Society (Minor)","TRAC is important to me because it allows me to make meaningful connections with other students on campus and through peer-to-peer collaborative effort. In turn, TRAC allows me to enhance my own skills as a student and allows me to learn something new at every conference. ",mac425@lehigh.edu
huh224,"ENGR 005","Huda Hagos",she/her,"Philadelphia, Pennsylvania",2024,"Environmental Studies, Political Science","I'm extremely passionate about all things environmental and social justice. I love to learn how people think and explore the world through different people's eyes. TRAC provides me with the perfect opportunity to do so. I get to learn from people of different majors and explore the writing process from their perspectives.",huh224@lehigh.edu
jrd825,"ENGR 005","Jack Davis",he/him,"Cheshire, CT",2025,"Industrial and Systems Engineering, Health Medicine and Society","Hello everyone! On my free time I enjoy playing video games with my friends or watching Netflix. I have enjoyed my time with the TRAC program so far and have been TRAC'ing ENGR 005. I would love to see the program become it's own academic department in the coming years.",jrd825@lehigh.edu
crs225,"ENGR 005","Carson Stotler",he/him,"Berkeley Springs, WV",2025,"Computer Science, Statistics","My career goal is to work in the tech field as a computer scientist and possibly be able to tie in my interest of sports statistics into my future career. I am really interested in weightlifting and overall health and wellness. A book I would recommend is Atomic Habits, it is a really good influential read!",crs225@lehigh.edu
jkk225,"ENGR 005","Julia Klayman",she/her,"North Woodmere, New York",2025,"Global Studies, Political Science, Anthropology","Hi! Some things I like to do are cook, play tennis, and watch Grey’s Anatomy. I joined TRAC because I love to explore subjects outside of my discipline, and TRAC allows me to do just that! I love to travel, and this past summer I did an internship in Uganda and this upcoming summer I’m going back to do research!",jkk225@lehigh.edu
smt225,"ENGR 005","Sonia Trinkle",she/her,"Westport, CT",2025,"Biomechanical Engineering","Hi! Some of my hobbies are running, yoga, and listening to music & podcasts. A fun fact about me is that I have dual citizenship in the U.S. and Ireland. My favorite part about the TRAC program is helping other students with their writing while also developing and transforming my own abilities as a scholar. ",smt225@lehigh.edu
jeb225,"ENGR 005","Jessica Berman",she/her,"West Hartford, CT",2025,"Population Health, Chinese","Hi everyone! This is my first year being a TRAC fellow and I am so excited! I joined TRAC because I have a passion for aiding others and wanted to improve my communication skills. Outside of class, I enjoy baking, playing tennis, and watching movies. A fun fact about me is that I have been studying Mandarin for 6 years!",jeb225@lehigh.edu
ssg225,"ENGR 005","Sebastian Gaertner",he/him,"Kirkland, Washington",2025,"Cognitive Science, Data Science, Business","Hello! I enjoy listening to music and taking walks. One of my favorite things in the TRAC program is being able to read so many different peoples writing. It's amazing to see how everyone has their own unique style. I have TRAC'ed ENGR 005.",ssg225@lehigh.edu
rfd225,"ENGR 005","Rylin Douthit",she/her,"Wilmette, IL",2025,"Major: Psychology and Health, Medicine, & Society Minor: Spanish ","Hi! I am super grateful to be a part of the TRAC program and it is something I look forward to each day. I am currently TRACing the ENGR 005 class and I've really enjoyed the opportunity to work with students in a major concentration that I've never been exposed to. Looking forward to being part of this program throughout my next semesters at Lehigh!",rfd225@lehigh.edu
gek224,"ENGR 005","Gabrielle",she/her,"North Caldwell, NJ",2024,"Major: Management Minor: Sociology","I am a junior at Lehigh who is studies business, loves writing, and enjoys having fun with friends! A fun fact about me is that I have a younger brother and that I am allergic to peanuts. A TV show I recommend is ""Glee"" because it is my favorite show and the music is incredible. I decided to join TRAC to immerse myself in a community of hard-working, talented, and passionate individuals! ",gek224@lehigh.edu
bek324,"ENGR 005","Brendan Karnish",he/him,"Marlton",2024,"Computer Science and Business, Physics","Hey everyone, my name is Brendan and I am an aspiring quantum computing engineer. Some things I like to do are play ice hockey, read books, write, and restore old cars. ",bek324@lehigh.edu
nid225,"ENGR 005","Niija Douglas",she/her,"West Hartford",2025,"Major: Computer Science Engineering, Minors: Data Science, Economics","Hi! Some of my hobbies include playing lacrosse and trying new foods. I TRAC because I have always loved helping improve the work of my friends and was excited to be able to do so on a larger scale. I recommend  the Netflix series Money Heist!",nid225@lehigh.edu
cjm224,"ENGR 005","Cj Marina",he/him,"Stroudsburg",2024,"Accounting, Finance, History","My biggest passion is the intersection of sustainability and business! Besides that, I'm also a twin, have three other siblings, and my favorite hobby is playing with my dog Matilda Grace. Finally, Peaky Blinders is the best TV show, ever. ",cjm224@lehigh.edu
ajp224,"ENGR 005","Alex Patti",he/him,"Blue Bell, PA",2024,"Finance, Accounting","Hello! Some hobbies of mine are listening to music, watching movies, and playing golf. I am a member of the swim team and have been doing it competitively for over 10 years. I am excited to continue to work as a TRAC Fellow and get exposure to new courses each semester. I have previously worked with BUS003.",ajp224@lehigh.edu
gvp225,"ENGR 005","Genevieve Powell",she/her,"Windhoek, Namibia",2025,"IDEAS (concentrating in Mechanical Engineering and Sociology and Psychology)","Hi! I am an international student from Southern Africa and I have loved being here at Lehigh so far. The TRAC Program has been the most rewarding experience, and being able to connect with and learn from so many people on campus is so fulfilling. When I can, I love painting, traveling, and good coffee. ",gvp225@lehigh.edu
iss225,"ENGR 005","Isabelle Spirk",she/her,"Doylestown, PA",2025,"Political Science & Environmental Studies, Asian Studies","I am interested in fields of ecology, specifically environmental humanities and sustainability policies and politics, as well as interdisciplinary studies of religion and Asian studies.  In general, I love learning.  TRAC is a natural extension of this intellectual curiosity and provides an opportunity for me to explore nontraditional topics in education, branch out by learning more about subjects I am unfamiliar with, and collaborate with peers and faculty.  Beyond TRAC, I enjoy reading books such as The Night Circus and going to the gym (at least sometimes).",iss225@lehigh.edu
cmd225,"ENGR 005","Casey Dolan",she/her,"Bloomfield, NJ",2025,"Materials Science and Engineering, Economics","When I first joined TRAC, I had no idea how much of a positive impact it would have on me. I've learned so much about the value of peer to peer communication and how being vulnerable is one of our greatest strengths. I am the secretary of LU eNABLE, an on campus club dedicated to designing and 3D printing prosthetics for those in need. I am also an active member of the women's club basketball team and the society of women engineers. A TV show I recommend is New Girl. It's super funny and I've watched it five times through. I am so excited to continue being involved in the TRAC program throughout the rest of my time at Lehigh!",cmd225@lehigh.edu
mra225,"ENGR 005","Marissa Argen",she/her,"Boonton Twp, NJ",2025,"Biology, Spanish & Hispanic Studies","Hi! I'm currently on the pre-health track with the intention to pursue a career as either a physician assistant or a veterinarian. In my free time, I enjoy drawing, painting, reading, listening to music, and being outside! I am incredibly grateful to be a part of TRAC because it has allowed me to meet new friends and continue to explore reading/writing while helping other students succeed. ",mra225@lehigh.edu
akt224,"ENGR 005","Akari Takahashi",she/her,"Tokyo",2024,"Biology, HMS","During my free time, I like to listen to music, draw, play tennis, and watch musicals. Since I grew up in Japan, the cultural background may be different from that of native speakers, but I would like to use my unique perspective and way of thinking in TRAC. Previously I have TRAC'ed BUS 003 and BIOS 042. ",akt224@lehigh.edu
jnc425,"ENGR 005","Jeremy Cohen",he/him,"Philadelphia, PA",2025,"Industrial & Systems Engineering","I love playing disc golf, watching most shows on HBO, and supporting the Philly sports teams. Through TRAC, I really enjoy helping students talk out their ideas and elevate their work. ",jnc425@lehigh.edu
missing,"ENGR 005","Lee",‎,"",‎,"","",missing@lehigh.edu
missing,"ENGR 005","Lyon",‎,"",‎,"","",missing@lehigh.edu 
missing,"ENGR 005","Kesh",‎,"",‎,"","",missing@lehigh.edu 
missing,"ENGR 005","Mucharemba",‎,"",‎,"","",missing@lehigh.edu 
missing,"ENGR 005","Mack",‎,"",‎,"","",missing@lehigh.edu
hideMe,"ENGR 005","",‎,"",‎,"","",missing@lehigh.edu
hideMe,"ENGR 005","",‎,"",‎,"","",missing@lehigh.edu`;
