
export const LT = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email
bcn223,"LT","Brian Nasielski",he/him,"Mount Laurel, NJ",2023,"Chemical Engineering and Biochemistry Double Major","I am currently a senior at Lehigh and serving as a Veteran-Mentor Fellow on the Leadership Team. During my time in the program I have worked closely with ENG005, BIOS042, EES379 and the senior engineering capstone design course. Being in the TRAC program has helped shape the way I approach problems and communicate with others, and it has proven to be critical in my approach to other involvements such as undergraduate research, summer internships, and even being a part of Greek Life at Lehigh. Outside of the program and In my free time I enjoy exercising and spending time outside, especially down the shore.  ",bcn223@lehigh.edu
cep223,"LT","Caroline Palmer",she/her,"Princeton Junction, NJ",2023,"Biology, Religion","Here at Lehigh, I am the president of the LU Bhangra dance team, I am a Martindale Honors Associate (ask me about this, it's so cool!), and I have my own embroidery business. Next year, I'll be in dental school. I TRAC because TRAC gives me a voice and it allows me to learn, teach and reflect. Being surrounded by different, charismatic people allows for such a wonderful exchange of ideas! Specifically in TRAC I am a veteran fellow mentor fellow. ",cep223@lehigh.edu
cjs323,"LT","Caroline Spindel",she/her,"Murfreesboro, TN",2023,"IDEAS, Electrical Engineering, Psychology, Philosophy","The 2022-2023 school year is my third year as a TRAC Fellow. I have TRAC'ed four courses (ENGR 095, REL 122, MLL 090), as well as working as the Lead Fellow for ANTH 011. For the 2022-2023 school year, I am working as a Veteran Fellow Mentor Fellow as a member of the Leadership Team. My favorite aspects of TRAC are conferencing, hosting Veteran Fellow Seminars, and participating in the recruitment process. ",cjs323@lehigh.edu
cab223,"LT","Charlotte Brown",she/her,"Westchester, NY",2023,"Philosophy, Graphic Design, Marketing","Hiya! I love reading and writing and the TRAC program has proven to be the perfect application of those passions, with the addition of helping others and being part of a caring community. In my free time, I teach yoga at Taylor Gym and enjoy listening to music and spending time with my friends.",cab223@lehigh.edu
jjc422,"LT","John Cascio",he/him,"Bellmore, NY",2023,"Mechanical Engineering and Finance, Aerospace Engineering and Economics","I am currently the Managing Fellow of the TRAC Program, and in the past I was a member of the LT and TRAC'ed courses such as HSE 472, MAT 033, BUS 003, and ENGR 005.  On campus, I am a Head Gryphon in Taylor House and also a member of Phi Sigma Pi Honors Fraternity, where I served as Treasurer and President.  Some of my favorite hobbies include attending concerts, going to theme parks, and skiing.  I am also interested in astronomy research and other aerospace developments. ",jjc422@lehigh.edu
mig223,"LT","Michaela Gualano",she/her,"Mamaroneck, NY",2023,"Finance, Entrepreneurship & Real Estate ","I ran to be an Associate Fellow Mentor Fellow on the basis of wanting to emulate the idea of “Process of Product” in my teaching, as I want other fellows to know that it’s about learning along the way. It is about discovering yourself, new ways to help other students, and new ways to learn/ teach. ",mig223@lehigh.edu
missing,"Niche","Abby Buckham",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
hideMe,"LT","",‎,"",‎,"","",missing@lehigh.edu
hideMe,"LT","",‎,"",‎,"","",missing@lehigh.edu`;
`;

// lin,name,pronouns,picture,hometown,year,semester,yearsIn,majorMinor,info
// id,assignment,name,pronouns,hometown,year,majorMinor,info,email  ** want
// 856318382,"LT Fellow",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
// 123318382,"LT Fellow 2",she/her,123318382,"Houston, TX",2024,spring,3,Music,"Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
// 55612382,"LT Fellow 3",he/him,55612382,"Brooklyn, NY",2025,fall,1,Business,"Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
// 856318382,"LT Fellow 4",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
// 856318382,"LT Fellow 5",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"
// 856318382,"LT Fellow 6",they/them,856318382,"Perkasie, PA",2023,spring,2,"Computer Science, Japanese","Hello! My name is Jay Piazza and I’m a junior majoring in psychology. I’m originally from Sacramento county and was drawn to Chico State because of its beautiful campus and surrounding landscape. I enjoy writing and building on my skills every year through various term papers, especially those that relate to psychology. In my free time I enjoy watching movies, playing video games, and cooking. I look forward to working with students and helping them improve and gain confidence in their writing skills!"`;
