export const Niche = `id,assignment,name,pronouns,hometown,year,majorMinor,info,email,focus
jct324,"Niche","Joss Tripoli",they/them,"Perkasie, PA",2023,"Computer Science, Japanese","Hello! Some things I like to do are listen to music, juggle, and make art. Software and web development are passions of mine, so I am excited to be working on the TRAC website this semester. I hope to improve the website's branding & consistency, presence, information, and functionality. Previously I have TRAC'ed BUS 003 and BIOS 042.",jct324@lehigh.edu,"Website"
agk423,"Niche","Alex Kline",he/him,"Mountain Top, PA",2023,"IDEAS B.S., C.S. B.S.","I love skiing and making music. I love building software. I am totally obsessed with cars and auto racing, especially F1. I like TRAC because it gets students more involved in the writing process and helps many underclassmen transition to writing in college. ",agk423@lehigh.edu, "Immediate feedback"
trg224,"Niche","Thiyara Girihagama",she/her,"Colombo, Sri Lanka",2024,"B.S Economics and Computer Science","I'm an international student from Sri Lanka. In my free time I enjoy playing tennis, hanging out with friends, reading, and playing piano. I also enjoy observational astronomy and astrophysics research. My other research entails projects in the field of financial engineering/quantitative finance. I love TRAC for the amazing people I've met and conversations I've had, as well as for how it helps me keep my goals and ideas grounded and in perspective. I have previously TRAC'ed ENGR005 and REL090. ",trg224@lehigh.edu, "Speaking Fellow"
krm422,"Niche","Katelyn McNamara",she/her,"Alexandria, Virginia",2022 for undergraduate degree (2023 for graduate degree),"Masters in Management, Major in Architecture, Minor in Marketing","I am a current graduate student in Lehigh's Master's in Management program. This is my 4th year as a TRAC Fellow and it has been one of my most rewarding experiences at Lehigh. During the past few years, I have worked with the Sociology and Business Communications classes as well as working as a Fellow while studying abroad in Florence. Currently, I am working as a Niche Fellow with the TRAC 100 seminar and am assisting our Associate Fellows as they complete their Self-Design projects. I love the work that we do in TRAC and I wish every student at Lehigh could work with a Fellow at some point in their education.",krm422@lehigh.edu, "TRAC 100"
jaw224,"Niche","Jordyn Whalen",she/her,"Boston, MA",2024,"Biology","Hi! Outside of TRAC, I enjoy hiking, swimming and art projects. I love TRAC because it is the place at Lehigh where I feel like I can make someone else's day better and we have such a great positive community. After Lehigh, I hope to go to medical school and work in underserved areas. I have worked with BUS003 students and this semester I am doing an independent niche fellowship on community improvement for the program. ",jaw224@lehigh.edu, "Peer Coaching"
missing,"Niche","Bisceglia",‎,"",‎,"","",missing@lehigh.edu,"Alumni"
missing,"Niche","Krishnamoorthy",‎,"",‎,"","",missing@lehigh.edu,"TRAC 100"
missing,"Niche","Crispe",‎,"",‎,"","",missing@lehigh.edu,"Speaking Fellows"
missing,"Niche","Cox",‎,"",‎,"","",missing@lehigh.edu,"Speaking Fellows"`;

